name: Extract Terraform Version
description: Outputs version of Terraform from a specified configuration file.
inputs:
  directory:
    required: false
    description: The directory path to the folder containing the configuration file with the Terraform version setting.
  file:
    required: false
    description: The filename (or glob pattern) of the configuration file(s) that contain the Terraform version setting.
  pattern:
    required: false
    description: The regex pattern used to search for the Terraform version in the configuration file.
outputs:
  required_version:
    description: The Terraform version or version constraint specified in the configuration file.
    value: ${{ steps.main.outputs.required_version }}
runs:
  using: composite
  steps:
    - run: pip install -r "${GITHUB_ACTION_PATH:-.}/requirements.txt"
      shell: bash

    - id: main
      run: python "$GITHUB_ACTION_PATH/src/main.py"
      shell: bash
      env:
        directory: ${{ inputs.directory }}
