name: Extract Terraform Version
description: Outputs version of Terraform from a specified configuration file.
inputs:
  directory:
    required: false
    description: The file path to the configuration file containing the terraform version setting.
  file:
    required: false
    description: The filename (or wildcard filter) of the configuration file containing the terraform version setting.
  pattern:
    required: false
    description: The pattern to search for in the configuration file.
outputs:
  required_version:
    description: The version of Terraform as specified in the configuration file.
    value: ${{ steps.main.outputs.required_version }}
runs:
  using: composite
  steps:
    - run: pip install -r "${GITHUB_ACTION_PATH:-.}/requirements.txt"
      shell: bash

    - id: main
      run: python "$GITHUB_ACTION_PATH/src/main.py"
      shell: bash
      env:
        directory: ${{ inputs.directory }}
