name: Manage GitHub Project
description: Adds issues or pull requests to a specified GitHub project.
inputs:
  project-url:
    description: URL of the GitHub project to add issues or pull requests to.
    required: true
  github-token:
    description: GitHub token, required if not using app-id and private-key.
    required: false
  app-id:
    description: GitHub App ID, required if not using github-token.
    required: false
  private-key:
    description: Private key for the GitHub App, required if not using github-token.
    required: false
runs:
  using: "composite"
  steps:
    # Determine repository name when using App ID and private key
    - name: Extract repository name without owner
      id: extract-repo
      if: inputs.app-id && inputs.private-key
      shell: bash
      run: |
        repo_name="${GITHUB_REPOSITORY##*/}"
        echo "Repository name without owner: $repo_name"
        echo "repo_name=$repo_name" >> $GITHUB_ENV
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    # Create GitHub App token if app-id and private-key are provided
    - name: Create GitHub App Token
      id: token
      if: inputs.app-id && inputs.private-key
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ env.repo_name }}

    # Add issue to project
    - name: Add issue to project
      if: github.event_name == 'issues'
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ steps.token.outputs.token || inputs.github-token }}

    # Add pull request to project
    - name: Add pull request to project
      if: github.event_name == 'pull_request'
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ steps.token.outputs.token || inputs.github-token }}
